import Head from 'next/head'
import Footer from '../component/Footer/Footer'
import Image from 'next/image'
import add from '../public/image/add.jpg'
import Header from '../component/Header/Header'
import MainSlider from '../component/Slider/MainSlider'
import Featured from '../component/MainPgaeList/Featured'
import NewTracks from '../component/MainPgaeList/NewTracks'
import LatestPodcasts from '../component/MainPgaeList/LatestPodcasts'
import NewAlbums from '../component/MainPgaeList/NewAlbums'
import RecentlyAdded from '../component/MainPgaeList/RecentlyAdded'
import BestofMonth from '../component/MainPgaeList/BestofMonth'
import TopPlayList from '../component/MainPgaeList/TopPlayList'
import TopArtists from '../component/MainPgaeList/TopArtists'
export default function Home() {
  return (
    <div>
      <Head>
        <title>soundHeaven</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <MainSlider />
      <Featured />
      <NewTracks />
      <div className='my-5 container-sm mx-auto'>
        <Image src={add} alt='add' className='banner' />
      </div>
      <LatestPodcasts />
      <NewAlbums />
      <RecentlyAdded />
      <BestofMonth />
      <TopPlayList />
      <TopArtists />
      <Footer />
    </div>
  )
}
